- name: Network Getting Started First Playbook Extended
  gather_facts: false
  hosts: java-servers
  tasks:
    - name: install java runtime
      apt:
        name: openjdk-11-jdk
        update_cache: yes

    - name: deploy artifact library to staging env 
      copy:
        src: target/classes/com
        dest: /home/

